### ISSUE TITLE
Rerender not working in my case

### ISSUE THREAD

**Issue by m4r1vs** [mobxjs/mobx-preact#11]
So, I am using [preact-router](https://github.com/developit/preact-router) for routing and I have a file `routes.js` looks like this:
```js
module.exports = [
    {
        path: '/',
        component: () => import('./component').then(module => module.default)
    },
    {
        path: '/route',
        component: () => import('./second_one').then(module => module.default)
    },
]
```
Then in `router.js` I have following setup:
```js
import { h, Component } from 'preact'
import PreactRouter from 'preact-router'

import {
	AsyncRoute
} from 'utils'

// the file above
import routes from './routes'

export default class Router extends Component {

	render = () => (
		<PreactRouter>
			{routes.map(route => <AsyncRoute path={route.path} loadFunction={route.component} />)}
		</PreactRouter>
	)
}
```
and then `component.js` like this:
```js
import { h } from 'preact'
import { inject, observer } from 'mobx-preact'

export default inject('myStore')(observer(({ myStore }) => (
    <div>{myStore.name}</div>
)))
```
The problem now is that when I update `name` in `myStore` the observer doesn't get fired and `component.js` doesn't update. It does however update in two cases:
1. I inject the same variable into `router.js` and cause this component to re-render on change.
2. I remove the `routes.map()` from `router.js` and just put the components in there.

So to me it seems like the observer somehow doesn't catch changes when the component was injected by the map() function. Option one is just stupid and option two is rather unpractical because in reality I have many, many more routes in `routes.js` and this is much cleaner.

**Comment by mweststrate** [comment]
Do you see any warnings about mobx being loaded twice?

Op za 20 jan. 2018 22:59 schreef Marius Niveri <notifications@github.com>:

**Comment by m4r1vs** [comment]
@mweststrate, No, i have mobx strict mode activated but still no erros/warnings by mobx. I think this might not even be 100% related to `mobx-preact` but more likely to some general thing in `preact`/`react`, I've already debugged it for hours but can't really find anything except for it not working with map()

**Comment by mweststrate** [comment]
Best create a small reproduction project then :)

Op zo 21 jan. 2018 om 00:43 schreef Marius Niveri <notifications@github.com

**Comment by m4r1vs** [comment]
Did so: https://github.com/m4r1vs/mobx-preact-debugging, in there everything works as expected but without using webpack import() yet. So not really related to mobx-preact

**Comment by m4r1vs** [comment]
Yep, and now even with all async things in the reproduction thing still working, really weird :D

**Comment by m4r1vs** [comment]
Okay, just figured out that both `autorun` and `reaction` get triggered even tho `mobx-preact` doesn't re-render. I looked a bit at your source code but didn't really learn much new from in there. How do you determine if the component should be re-rendered? If I can find a fix I will make a PR asap

**Comment by philmander** [comment]
Can you replicate in your test repo now?

**Comment by m4r1vs** [comment]
@philmander I updated the repo now. Just clone it and `yarn start/npm start`. There's a console.log after a few ms that says 'Router should have rerendered' when the store updates a value that should cause the router to re-render. It doesn't do that for me :/

**Comment by m4r1vs** [comment]
If you click `lol` and then `home` again the router however does update, it only doesn't adapt to changes automatically

**Comment by m4r1vs** [comment]
Okay, my bug was caused by the fact that I called an action that updates the store from an API in `componentWillMount`, maybe the API updated the store at exact the same time `render()` was called which may have caused a rerender not to occur?

**Comment by philmander** [comment]
Marius, I've lost track of this issue. Could you please create a new issue clearly stating the problem and steps to reproduce? Thanks
