### ISSUE TITLE
On production build: TypeError: Cannot call a class as a function, dev server works fine

### ISSUE THREAD

**Issue by pieterbergwerff** [mobxjs/mobx-preact#13]
In my app I use preact (preact-compat) & mobx-preact, in development mode (webpack-dev-server) everything works fine but when yarn build & yarn start my app, I get the following error message.

![screen shot 2018-04-03 at 23 04 10](https://user-images.githubusercontent.com/1438112/38275973-e74508f2-3793-11e8-818e-2c69c94ca890.png)

Anyone any ideas?

**Comment by philmander** [comment]
Hi Pieter, at a glance, using `ReactDOMServer` looks a bit fishy to me. You should use [preact-render-to-string](https://github.com/developit/preact-render-to-string).

I think you can also alias it like this:

```json
"alias": {
    "react-dom/server": "preact-compat/server"
}```

Although, I always just use it directly.
